### ISSUE TITLE
About entrypoint support

### ISSUE THREAD

**Issue by Thesola10** [tttapa/py-build-cmake#2]
https://github.com/tttapa/py-build-cmake/blob/03ee59c54f723dd8685587ad7c9b17db100dbb23/src/py_build_cmake/build.py#L433

I'm noticing that your module relies on `flit` to package the Python part of modules.
Is something preventing you from passing the `[project.scripts]` config through to `flit` untouched?

**Comment by tttapa** [comment]
> Is something preventing you from passing the [project.scripts] config through to flit untouched?

Apart from not finding the time to have a look at it, no :)

It should now be supported in version [0.0.6](https://github.com/tttapa/py-build-cmake/releases/tag/0.0.6).
