### ISSUE TITLE
Bug: exception when try to install to subfolder with dist-info

### ISSUE THREAD

**Issue by ilya-lavrenov** [tttapa/py-build-cmake#30]
Exception
![image](https://github.com/tttapa/py-build-cmake/assets/2566854/a8918b91-353c-4848-8020-65ddc9ad48b9)

Cmake code:
```cmake
install(FILES "${openvino_tokenizers_SOURCE_DIR}/LICENSE"
              "${openvino_tokenizers_SOURCE_DIR}/third-party-programs.txt"
              "${openvino_tokenizers_SOURCE_DIR}/SECURITY.md"
        DESTINATION "${PY_BUILD_CMAKE_PACKAGE_NAME}-${PY_BUILD_CMAKE_PACKAGE_VERSION}.dist-info/licenses"
        COMPONENT openvino_tokenizers_licenses
        EXCLUDE_FROM_ALL)
```
When install to `"${PY_BUILD_CMAKE_PACKAGE_NAME}-${PY_BUILD_CMAKE_PACKAGE_VERSION}.dist-info` - works well.

**Comment by ilya-lavrenov** [comment]
Ok, if it's not easy to fix, we can close ticket.

`scikit-build-core` creates `licenses` subfolder within `dist-info`, that is why I supposed it's easy to fix.

Example of such package https://pypi.org/project/openvino-tokenizers/#files

**Comment by tttapa** [comment]
> Ok, if it's not easy to fix, we can close ticket.

Is suspect that the fix will be easy enough, but it should be fixed in the `distlib` package, not in the `py-build-cmake` package.

**Comment by ilya-lavrenov** [comment]
`scikit-build-core` WAs the issue somehow.

But maybe that project does not use `distutils`
