### ISSUE TITLE
find_package(Python3 3.13 ...) fails on Windows w/ pypa/cibuildwheel

### ISSUE THREAD

**Issue by nickelpro** [tttapa/py-build-cmake#38]
When running `py-build-cmake >= v0.3.0a1` under Windows CI with `pypa/cibuildwheel` targeting Python 3.13, `FindPython3` cannot, well, find Python 3.

```
CMake Error at C:/Program Files/CMake/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find Python3 (missing: Python3_LIBRARIES Python3_INCLUDE_DIRS
  Development.Module) (Required is at least version "3.13")
```

~~I suspect this is the case anytime the system Python version != the Nuget installed version from cibuildwheel but haven't investigated.~~ CMake can't find the Python roots installed by cibuildwheel on Windows or MacOS.

"Reproducible" example is here: https://github.com/nickelpro/py_cmake_test

Build logs for 0.2.0a14: https://github.com/nickelpro/py_cmake_test/actions/runs/12172100616/job/33950179183

Build logs for 0.3.2: https://github.com/nickelpro/py_cmake_test/actions/runs/12172132448/job/33950270851

~~I've confirmed this happens for all 0.3 versions, with `find_python`/`find_python3` as both `true` and `false`.~~

The problem is introduced by: https://github.com/tttapa/py-build-cmake/commit/c8e610478b40a503a22f6ee39b2c6734b4d801b7 , so one of those paths is helping CMake find what cibuildwheel did with the Python installation. I feel like this is sort of cibuildwheel's fault for not sanely setting up the environment in a way compatible with `FindPython3`, but it would still be nice if this just worked out of the box.

**Comment by nickelpro** [comment]
And for the MacOS build the wrong Python 3.13 is being found:

0.2.0a14
```
Found Python3: /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13
```

0.3.0a1
```
Found Python3: /opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13
```

**Comment by nickelpro** [comment]
This is caused by not having `Interpreter` included as a required component. Ok. Fine. That's an oddity I'm just going to live with.

**Comment by tttapa** [comment]
Thanks for the detailed report!  
I've reverted part of c8e610478b40a503a22f6ee39b2c6734b4d801b7, and added a test for `find_python` without the interpreter component.

That said, it is recommended to include the `Interpreter` component to allow CMake's FindPython to query it for some of the details such as the SOABI/EXT_SUFFIX. If you're cross-compiling, the situation is a bit more nuanced: in general you shouldn't include the `Interpreter` when cross-compiling, except on macOS, where the system can run x86_64-only, arm64-only and universal2 binaries (either natively or through emulation). The approach in the examples should work in most common cases:

https://github.com/tttapa/py-build-cmake/blob/b2f0da78da6620d14fc912891faaa8f15a864acb/examples/pybind11-project/cmake/QueryPythonForPybind11.cmake#L13-L18

**Comment by nickelpro** [comment]
This issue prompted me to hash this out with Brad and Marc upstream in CMake, so that issue is now floating around. Brad's current suggestion is the behavior I kinda expected to pop out of this:

https://gitlab.kitware.com/cmake/cmake/-/issues/26505#note_1601468

If you have any input about what `py-build-cmake` expects to happen here, or what you think is reasonable for CMake to require of its build environment, I'm sure the feedback would be appreciated.
